### PR TITLE
Move mocha from devDependencues to peerDependencies

### LINKED ISSUE #50: Missing (peer) dependency 'mocha'
`lib/MultiReporters.js` requires `mocha` but package.json has `mocha` in it's `devDependencies` but it should be in `peerDependencies`.

I currently have an issue where mocha reports that it can not load mocha-multi-reporters:
```
"mocha-multi-reporters" reporter not found
      throw new Error('invalid reporter "' + reporter + '"');
      ^
Error: invalid reporter "mocha-multi-reporters"
```
However mocha DOES find the reporter but it fails to load because the reporter fails to require mocha in our case.

### PR DESCRIPTION
**Pull request by mgroenhoff**
Fixes #50

I did this on a Windows machine but `npm run test` does not run so the pre-commit scripts did not run either.

### CODE REVIEW

**Comment by jesstelford** [comment]
Would love to see this one merged and released - is there anything I can do to help get it over the line @stanleyhlng?

**Comment by scream314** [comment]
I'm sure I'm missing something, but I still receive
```
"mocha-multi-reporters" reporter not found
No coverage information was collected, exit without writing coverage information
/opt/server/node_modules/mocha/lib/mocha.js:174
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "mocha-multi-reporters"
    at Mocha.reporter (/opt/server/node_modules/mocha/lib/mocha.js:174:13)
    at Object.<anonymous> (/opt/server/node_modules/mocha/bin/_mocha:220:7)
    at Module._compile (module.js:652:30)
    at Module.replacementCompile (/opt/server/node_modules/nyc/node_modules/append-transform/index.js:58:13)
...
```
with
```
    "mocha-multi-reporters": "https://github.com/mgroenhoff/mocha-multi-reporters#dcd1d46ec53b40392b9061fc57680c5a8fad73cb",
```
in `package.json`.

**Comment by mgroenhoff** [comment]
@scream314 Looking at your error this has nothing to do with `mocha-multi-reporters` not being able to find `mocha` (which is what this PR is for) and because `mocha` finds `mocha-multi-reporters`, not the other way arround. If you are using NPM or Yarn and you have `mocha` installed in either your `dependencies` or `devDependencies` then you most likely are running into another issue.

I have seen that error before though and it comes from:
https://github.com/mochajs/mocha/blob/5fc58458395d8a9bc75daae97042af78dc94cc7a/lib/mocha.js#L193
Try adding a `console.log(err)` inside the catch to assist in debugging
https://github.com/mochajs/mocha/blob/5fc58458395d8a9bc75daae97042af78dc94cc7a/lib/mocha.js#L163

If that seems to be an error comming from `mocha-multi-reporters` I think you are in bad luck because this module seems not to be maintained anymore.

**Comment by scream314** [comment]
@mgroenhoff
Thank you for your reply, I was just about to edit my comment... I was right, it was my fault, the module was installed at a wrong location.

**Pull request merged**
