### PR TITLE
Inherit from Base reporter so that process exit code is correct

### PR DESCRIPTION
**Pull request by hiddentao**
My tests were failing but the mocha process was exiting with a success code. This PR fixes that.

### CODE REVIEW

**Comment by stanleyhlng** [comment]
Thanks for the PR @hiddentao.  Just leave a minor comment.

**Comment by hiddentao** [comment]
Removed unused dependency on `q`

**Comment by stanleyhlng** [comment]
published [mocha-multi-reporters@1.1.2]

[mocha-multi-reporters@1.1.2]: https://github.com/stanleyhlng/mocha-multi-reporters/releases/tag/v1.1.2

**Comment by hiddentao** [comment]
Thanks

**Pull request merged**
